name: Build My Apps

on:
  push:
    branches:
      - main
      - master # Deixei as duas aqui, assim não importa qual nome sua branch tem, vai rodar!

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Atualizado para o Java 17, exigido pelas versões mais novas do Flutter

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk" # Caminho corrigido que pega todos os APKs gerados
          tag: v0.0.1
          allowUpdates: true # Permite que o GitHub atualize o mesmo APK se você der push de novo
          token: ${{ secrets.GITHUB_TOKEN }} # Corrigido para o token padrão do GitHub